### ISSUE TITLE
Example from documentation doesn't run

### ISSUE THREAD

**Issue by martino-vic** [lingpy/pyedictor#3]
If I run `$ edictor wordlist -d cldf/cldf-metadata.json mydataset` from my terminal, as stated in the docs, I get 

```
usage: edictor [-h] {wordlist} ...
edictor: error: unrecognized arguments: mydataset
```

If I run `$ edictor -h` I get

```
usage: edictor [-h] {wordlist} ...

EDICTOR command line interface.

positional arguments:
  {wordlist}
    wordlist  Convert a dataset to EDICTOR's sqlite format.
```

Looks like it only let's me pass a wordlist, not a cldf-meta file. Am I maybe using a wrong version?

Came here via this issue: https://github.com/martino-vic/ronatasbertawot/issues/3#issuecomment-1079646083

**Comment by LinguList** [comment]
Did you try this command:

```
$ edictor wordlist --dataset=cldf/cldf-metadata.json
```

?

**Comment by LinguList** [comment]
Because "wordlist" is the command switcher, a subcommand (right now, pyedictor hasn't any other commands, but we may add them eventually).

**Comment by LinguList** [comment]
If I just type `edictor wordlist` inside your folder, I get a result.

**Comment by LinguList** [comment]
`mydataset` is a dummy that serves for your dataset. Maybe I should make the description clearer.

**Comment by martino-vic** [comment]
> $ edictor wordlist --dataset=cldf/cldf-metadata.json

Ah, excellent, this worked, thank you.
