### ISSUE TITLE
How to include column COGID

### ISSUE THREAD

**Issue by martino-vic** [lingpy/pyedictor#4]
I'm running `$ edictor wordlist --dataset=cldf/cldf-metadata.json` (https://github.com/lingpy/pyedictor/issues/3) but the resulting [file](https://github.com/martino-vic/ronataswestoldturkic/blob/main/input_edictor.tsv) doesn't contain a column "COGID". Is there a way to include this information? It's at least included in the [forms.csv](https://github.com/martino-vic/ronataswestoldturkic/blob/main/cldf/forms.csv) in column "Cognacy". I'd need this column to look at alignments in EDICTOR.

**Comment by LinguList** [comment]
I think this is described (using --addon) in the code documentation but 
also in the blog post from last year? Can you check please?

**Comment by martino-vic** [comment]
Thanks! `edictor wordlist --addon="cogid_cognateset_id:cognacy"` worked out as described in the [blog post](https://calc.hypotheses.org/4432)!
