### ISSUE TITLE
Is there a way to load alignments when converting to the edictor-format?

### ISSUE THREAD

**Issue by martino-vic** [lingpy/pyedictor#5]
So I've added an automatic alignment to my data, which is stored in [cognates.csv](https://github.com/martino-vic/ronataswestoldturkic/blob/main/cldf/cognates.csv)'s col "Alignment". Is there a way to include this column when I run the `edictor wordlist` command? I looked at the source code, at the readme, and also at the blog post, but didn't find an answer in any of those. I just want to upload this file to EDICTOR, so I can manually fix wrong alignments.

**Comment by LinguList** [comment]
The table is called "cogid_alignment" I assume, so you may want to use `addon=cogid_alignment:alignment`?

**Comment by martino-vic** [comment]
Worked like a charm! Thanks for the help!
